apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: o8sbl0nxh-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe:e32a1d660fddb3efd9d1c97a31d0e0042d87832f@sha256:96ba6e5b780ca44aa2b6796c53be605552df31da1f53e035b55d1d0885945524
          name: container-image
